# cloudbuild.yaml
steps:
  
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'us-central1-docker.pkg.dev/white-fiber-362314/thet-100966131/assignment-server:$COMMIT_SHA', 
      '.'
    ]
    

  
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/white-fiber-362314/thet-100966131/assignment-server:$COMMIT_SHA'
    ]
   
options:
  logging: REGIONAL_USER_OWNED_BUCKET


