steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 
      'us-central1-docker.pkg.dev/white-fiber-362314/thet-100966131/[IMAGE_NAME]:$COMMIT_SHA', 
      '.'
    ]

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'us-central1-docker.pkg.dev/white-fiber-362314/thet-100966131/[IMAGE_NAME]:$COMMIT_SHA'
    ]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 
      'deploy', 
      'firstname-studentid-service', 
      '--image', 
      'us-central1-docker.pkg.dev/white-fiber-362314/thet-100966131/[IMAGE_NAME]:$COMMIT_SHA', 
      '--region', 
      'us-central1'
    ]

# Set log storage behavior to use only Cloud Logging
options:
  logging: CLOUD_LOGGING_ONLY
