# Define the build steps for Cloud Build
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/white-fiber-362314/thet-100966131:$SHORT_SHA', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/white-fiber-362314/thet-100966131:$SHORT_SHA']

# Specify the output images for this build
images:
  - 'gcr.io/white-fiber-362314/thet-100966131:$SHORT_SHA'

# Set a timeout for the build
timeout: '1200s'

# Define options for the build
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

# Artifacts and logs bucket configuration
artifacts:
  objects:
    location: 'gs://cloud-build-logs-white-fiber-362314'
    paths: ['**']

# Substitutions for dynamic values
substitutions:
  _REGION: 'us-central1'

# Trigger details
trigger:
  event: 'push'
  branch: 'main'

# Optional: Notifications for build results
notifications:
  pubsubTopic: 'projects/white-fiber-362314/topics/cloud-builds'
